# Generated by Django 2.2.5 on 2021-04-07 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='название продукта')),
                ('price', models.FloatField(default=0, verbose_name='цена товара')),
                ('description', models.TextField(verbose_name='описание продукта')),
                ('count', models.IntegerField(default=0, verbose_name='количество продуктов')),
                ('is_active', models.BooleanField(verbose_name='наличие продукта')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Category')),
            ],
        ),
    ]
